name: gauge_indicator
description: An animated, highly customizable, opensource, Flutter gauge widget.
version: 0.3.4
homepage: https://github.com/gonuit/gauge_indicator

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable:
  collection:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
